### ISSUE TITLE
Move plots to `output` branch / 单独存放 png 减小仓库体积

### ISSUE THREAD

**Issue by Vinfall** [icue/SteamWishlistCalendar#8]
因为 `output` 目录存放了图片并且会一直追踪历史，导致仓库大小膨胀得很离谱。花点时间研究了一下，大小变化 53MiB -> 724KiB。

想法就是把 `output/*.png` 放到单独的分支里（ics/json/txt 不变），然后每次跑 CI push 完再 checkout output，然后 `git commit --amend --no-edit`，这样 `output` 分支的历史就不会膨胀，毕竟追踪二进制图片的变化也没什么意义，只是需要一个存放的地方。

在 `main` 分支的 git 历史中删除 `output/*.png` 的部分：

```sh
git log -- output/*.png
git filter-branch --index-filter 'git rm --cached --ignore-unmatch output/*.png' HEAD

git push origin --force --all
```

`output` 分支初始化：
```sh
git checkout --orphan output

# Bash
rm !("output"/*.png)
# Zsh
rm -- ^output/*.png

git add .
git commit -m "initial commit"

git checkout main
python -m swc -i=xxx -D=True
git restore output/wishlist.ics
git checkout output
git add .
git commit -m "ics: update plot"
```

然后 push 到 GitHub 再在 workflow 里新增[下面这部分](https://github.com/Vinfall/SteamWishlistCalendar/blob/dc12eab3c4368ea4ea2a3ac59b914a24b09a06d3/.github/workflows/analyze-wishlist.yml#L54-L71)：

```yml
jobs:
  build:
    steps:
    # ...
      - name: checkout output branch
        uses: actions/checkout@v4
        with:
          ref: output

      - name: commit plots
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit --amend --no-edit

      - name: push plots to output branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: True
```

这个涉及force push没法直接PR，我就直接开issue了。
